// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/fern-demo/plantstore-go-root/v2/core"
	internal "github.com/fern-demo/plantstore-go-root/v2/internal"
	option "github.com/fern-demo/plantstore-go-root/v2/option"
	plant "github.com/fern-demo/plantstore-go-root/v2/plant"
	user "github.com/fern-demo/plantstore-go-root/v2/user"
)

type Client struct {
	Plant *plant.Client
	User  *user.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Plant:   plant.NewClient(options),
		User:    user.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
