// Code generated by Fern. DO NOT EDIT.

package plantstore

import (
	core "github.com/fern-demo/plantstore-go-root/v2/core"
	internal "github.com/fern-demo/plantstore-go-root/v2/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	405: func(apiError *core.APIError) error {
		return &MethodNotAllowedError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
}
