// Code generated by Fern. DO NOT EDIT.

package plantstore

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-demo/plantstore-go-root/v2/internal"
	big "math/big"
)

var (
	getPlantByIDRequestFieldPlantID = big.NewInt(1 << 0)
)

type GetPlantByIDRequest struct {
	// ID of the plant to retrieve
	PlantID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPlantByIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPlantID sets the PlantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPlantByIDRequest) SetPlantID(plantID int) {
	g.PlantID = plantID
	g.require(getPlantByIDRequestFieldPlantID)
}

var (
	searchPlantsByStatusRequestFieldStatus = big.NewInt(1 << 0)
)

type SearchPlantsByStatusRequest struct {
	// The status of plants to search for.
	Status *SearchPlantsByStatusRequestStatus `json:"-" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchPlantsByStatusRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPlantsByStatusRequest) SetStatus(status *SearchPlantsByStatusRequestStatus) {
	s.Status = status
	s.require(searchPlantsByStatusRequestFieldStatus)
}

var (
	searchPlantsByTagsRequestFieldTags = big.NewInt(1 << 0)
)

type SearchPlantsByTagsRequest struct {
	// Tags to filter plants (comma-separated).
	Tags []*string `json:"-" url:"tags,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchPlantsByTagsRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchPlantsByTagsRequest) SetTags(tags []*string) {
	s.Tags = tags
	s.require(searchPlantsByTagsRequestFieldTags)
}

var (
	plantFieldName      = big.NewInt(1 << 0)
	plantFieldCategory  = big.NewInt(1 << 1)
	plantFieldTags      = big.NewInt(1 << 2)
	plantFieldStatus    = big.NewInt(1 << 3)
	plantFieldCareLevel = big.NewInt(1 << 4)
)

type Plant struct {
	Name     *string      `json:"name,omitempty" url:"name,omitempty"`
	Category *string      `json:"category,omitempty" url:"category,omitempty"`
	Tags     []string     `json:"tags,omitempty" url:"tags,omitempty"`
	Status   *PlantStatus `json:"status,omitempty" url:"status,omitempty"`
	// Relative maintenance effort the plant requires, to help shoppers pick plants that match their experience level.
	CareLevel *PlantCareLevel `json:"careLevel,omitempty" url:"careLevel,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *Plant) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *Plant) GetCategory() *string {
	if p == nil {
		return nil
	}
	return p.Category
}

func (p *Plant) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *Plant) GetStatus() *PlantStatus {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *Plant) GetCareLevel() *PlantCareLevel {
	if p == nil {
		return nil
	}
	return p.CareLevel
}

func (p *Plant) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *Plant) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Plant) SetName(name *string) {
	p.Name = name
	p.require(plantFieldName)
}

// SetCategory sets the Category field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Plant) SetCategory(category *string) {
	p.Category = category
	p.require(plantFieldCategory)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Plant) SetTags(tags []string) {
	p.Tags = tags
	p.require(plantFieldTags)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Plant) SetStatus(status *PlantStatus) {
	p.Status = status
	p.require(plantFieldStatus)
}

// SetCareLevel sets the CareLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *Plant) SetCareLevel(careLevel *PlantCareLevel) {
	p.CareLevel = careLevel
	p.require(plantFieldCareLevel)
}

func (p *Plant) UnmarshalJSON(data []byte) error {
	type unmarshaler Plant
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = Plant(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *Plant) MarshalJSON() ([]byte, error) {
	type embed Plant
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *Plant) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Relative maintenance effort the plant requires, to help shoppers pick plants that match their experience level.
type PlantCareLevel string

const (
	PlantCareLevelEasy     PlantCareLevel = "easy"
	PlantCareLevelModerate PlantCareLevel = "moderate"
	PlantCareLevelExpert   PlantCareLevel = "expert"
)

func NewPlantCareLevelFromString(s string) (PlantCareLevel, error) {
	switch s {
	case "easy":
		return PlantCareLevelEasy, nil
	case "moderate":
		return PlantCareLevelModerate, nil
	case "expert":
		return PlantCareLevelExpert, nil
	}
	var t PlantCareLevel
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlantCareLevel) Ptr() *PlantCareLevel {
	return &p
}

var (
	plantResponseFieldID     = big.NewInt(1 << 0)
	plantResponseFieldName   = big.NewInt(1 << 1)
	plantResponseFieldStatus = big.NewInt(1 << 2)
	plantResponseFieldTags   = big.NewInt(1 << 3)
)

type PlantResponse struct {
	ID     *int     `json:"id,omitempty" url:"id,omitempty"`
	Name   *string  `json:"name,omitempty" url:"name,omitempty"`
	Status *string  `json:"status,omitempty" url:"status,omitempty"`
	Tags   []string `json:"tags,omitempty" url:"tags,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlantResponse) GetID() *int {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PlantResponse) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PlantResponse) GetStatus() *string {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PlantResponse) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *PlantResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PlantResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlantResponse) SetID(id *int) {
	p.ID = id
	p.require(plantResponseFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlantResponse) SetName(name *string) {
	p.Name = name
	p.require(plantResponseFieldName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlantResponse) SetStatus(status *string) {
	p.Status = status
	p.require(plantResponseFieldStatus)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlantResponse) SetTags(tags []string) {
	p.Tags = tags
	p.require(plantResponseFieldTags)
}

func (p *PlantResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PlantResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlantResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlantResponse) MarshalJSON() ([]byte, error) {
	type embed PlantResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PlantResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlantStatus string

const (
	PlantStatusAvailable PlantStatus = "available"
	PlantStatusPending   PlantStatus = "pending"
	PlantStatusSold      PlantStatus = "sold"
)

func NewPlantStatusFromString(s string) (PlantStatus, error) {
	switch s {
	case "available":
		return PlantStatusAvailable, nil
	case "pending":
		return PlantStatusPending, nil
	case "sold":
		return PlantStatusSold, nil
	}
	var t PlantStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlantStatus) Ptr() *PlantStatus {
	return &p
}

type SearchPlantsByStatusRequestStatus string

const (
	SearchPlantsByStatusRequestStatusAvailable SearchPlantsByStatusRequestStatus = "available"
	SearchPlantsByStatusRequestStatusPending   SearchPlantsByStatusRequestStatus = "pending"
	SearchPlantsByStatusRequestStatusSold      SearchPlantsByStatusRequestStatus = "sold"
)

func NewSearchPlantsByStatusRequestStatusFromString(s string) (SearchPlantsByStatusRequestStatus, error) {
	switch s {
	case "available":
		return SearchPlantsByStatusRequestStatusAvailable, nil
	case "pending":
		return SearchPlantsByStatusRequestStatusPending, nil
	case "sold":
		return SearchPlantsByStatusRequestStatusSold, nil
	}
	var t SearchPlantsByStatusRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SearchPlantsByStatusRequestStatus) Ptr() *SearchPlantsByStatusRequestStatus {
	return &s
}
