// Code generated by Fern. DO NOT EDIT.

package plantstore

import (
	assert "github.com/stretchr/testify/assert"
	testing "testing"
)

func TestEnumOauthScope(t *testing.T) {
	t.Run("NewFromString_write_plants", func(t *testing.T) {
		t.Parallel()
		val, err := NewOauthScopeFromString("write:plants")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, OauthScope("write:plants"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_read_plants", func(t *testing.T) {
		t.Parallel()
		val, err := NewOauthScopeFromString("read:plants")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, OauthScope("read:plants"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewOauthScopeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewOauthScopeFromString("write:plants")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
