// Code generated by Fern. DO NOT EDIT.

package plantstore

import (
	fmt "fmt"
)

type OauthScope string

const (
	// modify plants in your account
	OauthScopeWritePlants OauthScope = "write:plants"
	// read your plants
	OauthScopeReadPlants OauthScope = "read:plants"
)

func NewOauthScopeFromString(s string) (OauthScope, error) {
	switch s {
	case "write:plants":
		return OauthScopeWritePlants, nil
	case "read:plants":
		return OauthScopeReadPlants, nil
	}
	var t OauthScope
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OauthScope) Ptr() *OauthScope {
	return &o
}
