// Code generated by Fern. DO NOT EDIT.

package plantstore

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-demo/plantstore-go-root/v2/internal"
	big "math/big"
)

var (
	getUserByNameRequestFieldUsername = big.NewInt(1 << 0)
)

type GetUserByNameRequest struct {
	// Username of the user to retrieve
	Username string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUserByNameRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUserByNameRequest) SetUsername(username string) {
	g.Username = username
	g.require(getUserByNameRequestFieldUsername)
}

var (
	loginUserRequestFieldUsername = big.NewInt(1 << 0)
	loginUserRequestFieldPassword = big.NewInt(1 << 1)
)

type LoginUserRequest struct {
	// The username for login
	Username *string `json:"-" url:"username,omitempty"`
	// The password for login
	Password *string `json:"-" url:"password,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LoginUserRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoginUserRequest) SetUsername(username *string) {
	l.Username = username
	l.require(loginUserRequestFieldUsername)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoginUserRequest) SetPassword(password *string) {
	l.Password = password
	l.require(loginUserRequestFieldPassword)
}

var (
	userFieldID       = big.NewInt(1 << 0)
	userFieldUsername = big.NewInt(1 << 1)
	userFieldEmail    = big.NewInt(1 << 2)
)

type User struct {
	ID       *int    `json:"id,omitempty" url:"id,omitempty"`
	Username *string `json:"username,omitempty" url:"username,omitempty"`
	Email    *string `json:"email,omitempty" url:"email,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *User) GetID() *int {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *User) GetUsername() *string {
	if u == nil {
		return nil
	}
	return u.Username
}

func (u *User) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *User) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *User) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetID(id *int) {
	u.ID = id
	u.require(userFieldID)
}

// SetUsername sets the Username field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetUsername(username *string) {
	u.Username = username
	u.require(userFieldUsername)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *User) SetEmail(email *string) {
	u.Email = email
	u.require(userFieldEmail)
}

func (u *User) UnmarshalJSON(data []byte) error {
	type unmarshaler User
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = User(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *User) MarshalJSON() ([]byte, error) {
	type embed User
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *User) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	userAuthResponseFieldToken     = big.NewInt(1 << 0)
	userAuthResponseFieldExpiresIn = big.NewInt(1 << 1)
)

type UserAuthResponse struct {
	// Authentication token
	Token *string `json:"token,omitempty" url:"token,omitempty"`
	// Token expiration time in seconds
	ExpiresIn *int `json:"expiresIn,omitempty" url:"expiresIn,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserAuthResponse) GetToken() *string {
	if u == nil {
		return nil
	}
	return u.Token
}

func (u *UserAuthResponse) GetExpiresIn() *int {
	if u == nil {
		return nil
	}
	return u.ExpiresIn
}

func (u *UserAuthResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UserAuthResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserAuthResponse) SetToken(token *string) {
	u.Token = token
	u.require(userAuthResponseFieldToken)
}

// SetExpiresIn sets the ExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UserAuthResponse) SetExpiresIn(expiresIn *int) {
	u.ExpiresIn = expiresIn
	u.require(userAuthResponseFieldExpiresIn)
}

func (u *UserAuthResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UserAuthResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserAuthResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserAuthResponse) MarshalJSON() ([]byte, error) {
	type embed UserAuthResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UserAuthResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
