// Code generated by Fern. DO NOT EDIT.

package plant

import (
	context "context"

	plantstore "github.com/fern-demo/plantstore-go-root/v2"
	core "github.com/fern-demo/plantstore-go-root/v2/core"
	internal "github.com/fern-demo/plantstore-go-root/v2/internal"
	option "github.com/fern-demo/plantstore-go-root/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &plantstore.Plant{
//	    Name: plantstore.String(
//	        "Fern",
//	    ),
//	    Category: plantstore.String(
//	        "Indoor",
//	    ),
//	    Tags: []string{
//	        "green",
//	        "leafy",
//	    },
//	    Status: plantstore.PlantStatusAvailable.Ptr(),
//	}
//	client.Plant.AddPlant(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) AddPlant(
	ctx context.Context,
	request *plantstore.Plant,
	opts ...option.RequestOption,
) (*plantstore.PlantResponse, error) {
	response, err := c.WithRawResponse.AddPlant(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	request := &plantstore.Plant{
//	    Name: plantstore.String(
//	        "Fern",
//	    ),
//	    Category: plantstore.String(
//	        "Indoor",
//	    ),
//	    Tags: []string{
//	        "green",
//	        "leafy",
//	    },
//	    Status: plantstore.PlantStatusSold.Ptr(),
//	}
//	client.Plant.UpdatePlant(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdatePlant(
	ctx context.Context,
	request *plantstore.Plant,
	opts ...option.RequestOption,
) (*plantstore.PlantResponse, error) {
	response, err := c.WithRawResponse.UpdatePlant(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter plants based on their current status.
//
// Example:
//
//	request := &plantstore.SearchPlantsByStatusRequest{}
//	client.Plant.SearchPlantsByStatus(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SearchPlantsByStatus(
	ctx context.Context,
	request *plantstore.SearchPlantsByStatusRequest,
	opts ...option.RequestOption,
) ([]*plantstore.PlantResponse, error) {
	response, err := c.WithRawResponse.SearchPlantsByStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter plants based on associated tags.
//
// Example:
//
//	request := &plantstore.SearchPlantsByTagsRequest{}
//	client.Plant.SearchPlantsByTags(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SearchPlantsByTags(
	ctx context.Context,
	request *plantstore.SearchPlantsByTagsRequest,
	opts ...option.RequestOption,
) ([]*plantstore.PlantResponse, error) {
	response, err := c.WithRawResponse.SearchPlantsByTags(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a plant's details by its ID.
//
// Example:
//
//	request := &plantstore.GetPlantByIDRequest{
//	    PlantID: 1,
//	}
//	client.Plant.GetPlantByID(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetPlantByID(
	ctx context.Context,
	request *plantstore.GetPlantByIDRequest,
	opts ...option.RequestOption,
) (*plantstore.PlantResponse, error) {
	response, err := c.WithRawResponse.GetPlantByID(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
