// Code generated by Fern. DO NOT EDIT.

package plant_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	plantstore "github.com/fern-demo/plantstore-go-root/v2"
	client "github.com/fern-demo/plantstore-go-root/v2/client"
	option "github.com/fern-demo/plantstore-go-root/v2/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPlantAddPlantWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &plantstore.Plant{
		Name: plantstore.String(
			"Fern",
		),
		Category: plantstore.String(
			"Indoor",
		),
		Tags: []string{
			"green",
			"leafy",
		},
		Status: plantstore.PlantStatusAvailable.Ptr(),
	}
	_, invocationErr := client.Plant.AddPlant(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPlantAddPlantWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPlantAddPlantWithWireMock", "POST", "/plant", nil, 1)
}

func TestPlantUpdatePlantWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &plantstore.Plant{
		Name: plantstore.String(
			"Fern",
		),
		Category: plantstore.String(
			"Indoor",
		),
		Tags: []string{
			"green",
			"leafy",
		},
		Status: plantstore.PlantStatusSold.Ptr(),
	}
	_, invocationErr := client.Plant.UpdatePlant(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPlantUpdatePlantWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPlantUpdatePlantWithWireMock", "PUT", "/plant", nil, 1)
}

func TestPlantSearchPlantsByStatusWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &plantstore.SearchPlantsByStatusRequest{}
	_, invocationErr := client.Plant.SearchPlantsByStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPlantSearchPlantsByStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPlantSearchPlantsByStatusWithWireMock", "GET", "/plant/search/status", nil, 1)
}

func TestPlantSearchPlantsByTagsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &plantstore.SearchPlantsByTagsRequest{}
	_, invocationErr := client.Plant.SearchPlantsByTags(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPlantSearchPlantsByTagsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPlantSearchPlantsByTagsWithWireMock", "GET", "/plant/search/tags", nil, 1)
}

func TestPlantGetPlantByIDWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &plantstore.GetPlantByIDRequest{
		PlantID: 1,
	}
	_, invocationErr := client.Plant.GetPlantByID(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPlantGetPlantByIDWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPlantGetPlantByIDWithWireMock", "GET", "/plant/1", nil, 1)
}
