/*
Swagger Plant Store - OpenAPI 3.1

This is a sample Plant Store Server based on the OpenAPI 3.1 specification. It provides a comprehensive set of endpoints for managing plants, orders, and user authentication.  ### Key Features - **Rich API Documentation**: Includes detailed examples and schema definitions. - **Search Functionality**: Search for plants by tags or status. - **User-Friendly Endpoints**: Login, logout, and retrieve user information. - **Error Handling**: Clear and consistent error responses.  ### Developer Notes - Use `api_key` for store endpoints requiring authorization. - OAuth2 flow is available for plant-specific operations. 

API version: 1.0.18
Contact: support@buildwithfern.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plantstore

import (
	"encoding/json"
)

// checks if the Plant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Plant{}

// Plant struct for Plant
type Plant struct {
	Name *string `json:"name,omitempty"`
	Category *string `json:"category,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Status *string `json:"status,omitempty"`
	// Relative maintenance effort the plant requires, to help shoppers pick plants that match their experience level.
	CareLevel *string `json:"careLevel,omitempty"`
}

// NewPlant instantiates a new Plant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlant() *Plant {
	this := Plant{}
	return &this
}

// NewPlantWithDefaults instantiates a new Plant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlantWithDefaults() *Plant {
	this := Plant{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Plant) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plant) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Plant) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Plant) SetName(v string) {
	o.Name = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *Plant) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plant) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *Plant) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *Plant) SetCategory(v string) {
	o.Category = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Plant) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plant) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Plant) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Plant) SetTags(v []string) {
	o.Tags = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Plant) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plant) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Plant) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Plant) SetStatus(v string) {
	o.Status = &v
}

// GetCareLevel returns the CareLevel field value if set, zero value otherwise.
func (o *Plant) GetCareLevel() string {
	if o == nil || IsNil(o.CareLevel) {
		var ret string
		return ret
	}
	return *o.CareLevel
}

// GetCareLevelOk returns a tuple with the CareLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Plant) GetCareLevelOk() (*string, bool) {
	if o == nil || IsNil(o.CareLevel) {
		return nil, false
	}
	return o.CareLevel, true
}

// HasCareLevel returns a boolean if a field has been set.
func (o *Plant) HasCareLevel() bool {
	if o != nil && !IsNil(o.CareLevel) {
		return true
	}

	return false
}

// SetCareLevel gets a reference to the given string and assigns it to the CareLevel field.
func (o *Plant) SetCareLevel(v string) {
	o.CareLevel = &v
}

func (o Plant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Plant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CareLevel) {
		toSerialize["careLevel"] = o.CareLevel
	}
	return toSerialize, nil
}

type NullablePlant struct {
	value *Plant
	isSet bool
}

func (v NullablePlant) Get() *Plant {
	return v.value
}

func (v *NullablePlant) Set(val *Plant) {
	v.value = val
	v.isSet = true
}

func (v NullablePlant) IsSet() bool {
	return v.isSet
}

func (v *NullablePlant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlant(val *Plant) *NullablePlant {
	return &NullablePlant{value: val, isSet: true}
}

func (v NullablePlant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


