/*
Swagger Plant Store - OpenAPI 3.1

This is a sample Plant Store Server based on the OpenAPI 3.1 specification. It provides a comprehensive set of endpoints for managing plants, orders, and user authentication.  ### Key Features - **Rich API Documentation**: Includes detailed examples and schema definitions. - **Search Functionality**: Search for plants by tags or status. - **User-Friendly Endpoints**: Login, logout, and retrieve user information. - **Error Handling**: Clear and consistent error responses.  ### Developer Notes - Use `api_key` for store endpoints requiring authorization. - OAuth2 flow is available for plant-specific operations. 

API version: 1.0.18
Contact: support@buildwithfern.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plantstore

import (
	"encoding/json"
)

// checks if the UserAuthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAuthResponse{}

// UserAuthResponse struct for UserAuthResponse
type UserAuthResponse struct {
	// Authentication token
	Token *string `json:"token,omitempty"`
	// Token expiration time in seconds
	ExpiresIn *int32 `json:"expiresIn,omitempty"`
}

// NewUserAuthResponse instantiates a new UserAuthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAuthResponse() *UserAuthResponse {
	this := UserAuthResponse{}
	return &this
}

// NewUserAuthResponseWithDefaults instantiates a new UserAuthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAuthResponseWithDefaults() *UserAuthResponse {
	this := UserAuthResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *UserAuthResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAuthResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *UserAuthResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *UserAuthResponse) SetToken(v string) {
	o.Token = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *UserAuthResponse) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAuthResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *UserAuthResponse) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *UserAuthResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

func (o UserAuthResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAuthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expiresIn"] = o.ExpiresIn
	}
	return toSerialize, nil
}

type NullableUserAuthResponse struct {
	value *UserAuthResponse
	isSet bool
}

func (v NullableUserAuthResponse) Get() *UserAuthResponse {
	return v.value
}

func (v *NullableUserAuthResponse) Set(val *UserAuthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAuthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAuthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAuthResponse(val *UserAuthResponse) *NullableUserAuthResponse {
	return &NullableUserAuthResponse{value: val, isSet: true}
}

func (v NullableUserAuthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAuthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


