// Code generated by Fern. DO NOT EDIT.

package user

import (
	context "context"

	plantstore "github.com/fern-demo/plantstore-go-root/v2"
	core "github.com/fern-demo/plantstore-go-root/v2/core"
	internal "github.com/fern-demo/plantstore-go-root/v2/internal"
	option "github.com/fern-demo/plantstore-go-root/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &plantstore.LoginUserRequest{}
//	client.User.LoginUser(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) LoginUser(
	ctx context.Context,
	request *plantstore.LoginUserRequest,
	opts ...option.RequestOption,
) (*plantstore.UserAuthResponse, error) {
	response, err := c.WithRawResponse.LoginUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.User.LogoutUser(
//	    context.TODO(),
//	)
func (c *Client) LogoutUser(
	ctx context.Context,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.LogoutUser(
		ctx,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Retrieve user details using their username.
//
// Example:
//
//	request := &plantstore.GetUserByNameRequest{
//	    Username: "username",
//	}
//	client.User.GetUserByName(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetUserByName(
	ctx context.Context,
	request *plantstore.GetUserByNameRequest,
	opts ...option.RequestOption,
) (*plantstore.User, error) {
	response, err := c.WithRawResponse.GetUserByName(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
